services:
  db:
    image: mysql:8.0
    container_name: board-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: board
      TZ: Asia/Seoul
    ports:
      - "3307:3306"               # <-- 호스트 3307로 변경 (로컬 MySQL과 충돌 회피)
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    image: ghcr.io/junseong-github/mainproject-backend:latest
#    build:
#      context: ./mainProject
#      dockerfile: Dockerfile
    container_name: board-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/board?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: prod
      TZ: Asia/Seoul
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"

  frontend:
    image: ghcr.io/junseong-github/mainproject-frontend:latest
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
    container_name: board-frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  db_data:
