services:
  mysql:
    image: mysql:8.0
    container_name: mysql-erp
    environment:
      MYSQL_DATABASE: erp
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    ports:
      - "3307:3306"   # 선택: 호스트에서 접근 필요하면 열기
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-proot"]
      interval: 5s
      retries: 30

  backend:
    build: .
    container_name: app-backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      # ← 이것 하나로 'docker' 프로필이 자동 적용됨
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8081:8081"
