server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: 250756

  jpa:
    hibernate:
      ddl-auto: validate          # ✅ 스키마는 검증만 (자동 생성/수정 안 함)
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true                 # ✅ Flyway 활성화
    # locations: classpath:db/migration   # (필요시) 마이그레이션 경로 기본값이라 생략 가능

logging:
  level:
    org.hibernate.SQL: debug
