# 공통 설정
server:
  port: 8080

spring:
  profiles:
    # 로컬에서 별도 지정 안 하면 'local'이 기본 적용됨
    default: local

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: debug

---
# 로컬 프로필: 로컬 MySQL(3306) 사용
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/erp?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: 250756

---
# 도커 프로필: 같은 compose 네트워크의 mysql 서비스(3306) 사용
# (백엔드도 컨테이너에서 띄울 때)
server:
  port: 8081
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/erp?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: 250756
