name: CI (Build & Push)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: ghcr.io
      IMAGE_BACKEND: junseong-github/mainproject-backend
      IMAGE_FRONTEND: junseong-github/mainproject-frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- Backend ----------
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Ensure gradlew executable
        working-directory: mainProject
        run: chmod +x gradlew

      - name: Gradle build (skip tests for CI)
        working-directory: mainProject
        run: ./gradlew --no-daemon clean bootJar -x test --stacktrace

      # ---------- Frontend ----------
      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install & Build (frontend)
        working-directory: frontend
        run: |
          npm ci
          npm run build

      # ---------- Docker Push ----------
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./mainProject
          file: ./mainProject/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_BACKEND }}:latest
            ghcr.io/${{ env.IMAGE_BACKEND }}:${{ github.sha }}

      - name: Build & Push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_FRONTEND }}:latest
            ghcr.io/${{ env.IMAGE_FRONTEND }}:${{ github.sha }}
